  # environment variables
environment:
  path_to_sln: src/src.sln 
skip_tags: true
install:
  - choco install gitversion.portable -pre -y
  - cinst gitlink -version 2.4.1 -y
  - cinst dotnetcore-sdk --version 3.0.100-preview6-012264 --pre
  - dotnet new -i Microsoft.AspNetCore.Blazor.Templates
image: Visual Studio 2019 Preview
assembly_info:
  patch: false
before_build:
- ps: gitversion /l console /output buildserver
- cmd: msbuild %path_to_sln% /t:restore /p:PackageVersion=%GitVersion_FullSemVer%
- cmd: dotnet restore %path_to_sln%
build:
  project: '%path_to_sln%'
  verbosity: minimal
after_build:
- cmd: gitlink . -u https://github.com/%APPVEYOR_REPO_NAME% -b %APPVEYOR_REPO_BRANCH% -s %APPVEYOR_REPO_COMMIT% -f %path_to_sln%
- cmd: msbuild %path_to_sln% /t:Pack /p:PackageVersion=%GitVersion_FullSemVer%
artifacts:
- path: /src/**/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  skip_symbols: false
  artifact: /.*\.nupkg/